version: "3"
services:
  reltime_node:
    image: hyperledger/besu:22.1.0-RC5-SNAPSHOT
    container_name: "node-4"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/config.toml
volumes:
  .:
